<a href="https://colab.research.google.com/github/talhaanwarch/OffenseEval2020/blob/master/English/sub/sub1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive',force_remount=True)

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
#cd /content/drive/My Drive/dataset/OffenseEval2020/data

In [3]:
import numpy as np
import re
import nltk
from nltk.corpus import stopwords
import string
import pandas as pd
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.


True

In [0]:
# cd 'drive/My Drive/dataset/OffenseEval2020'

In [5]:
ls

drive/  sample_data/


In [0]:
# !mkdir data
# import zipfile
# with zipfile.ZipFile("task_a_distant.zip","r") as zip_ref:
#     zip_ref.extractall("data",pwd=b'sem2020-t12')

In [7]:
ls

drive/  sample_data/


In [0]:
train=pd.read_csv( '/content/drive/My Drive/dataset/OffenseEval2020/data/English/task_a_distant.tsv',sep="\t")

In [9]:
train.head()

id  ...       std
0  1159533701283352576  ...  0.187379
1  1159533703522992128  ...  0.145998
2  1159533703758061570  ...  0.140628
3  1159533703904800769  ...  0.187498
4  1159533705125343232  ...  0.097098

[5 rows x 4 columns]

In [0]:
#offensive 1
#not offensive 0

In [0]:
X_train=train['text']
y_train=train['average'].values

y_train[y_train>0.5]=1
y_train[y_train<0.5]=0
y_train=y_train.astype('int')


In [12]:
y_train[0:5]

array([0, 0, 1, 1, 1])

In [13]:
val=pd.read_csv('/content/drive/My Drive/dataset/OLID/data/olid-training-v1.0.tsv',sep="\t")
val.head()

id                                              tweet  ... subtask_b subtask_c
0  86426  @USER She should ask a few native Americans wh...  ...       UNT       NaN
1  90194  @USER @USER Go home you’re drunk!!! @USER #MAG...  ...       TIN       IND
2  16820  Amazon is investigating Chinese employees who ...  ...       NaN       NaN
3  62688  @USER Someone should'veTaken" this piece of sh...  ...       UNT       NaN
4  43605  @USER @USER Obama wanted liberals &amp; illega...  ...       NaN       NaN

[5 rows x 5 columns]

In [0]:
X_val=val['tweet']
y_val=val['subtask_a'].values

In [0]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [0]:
y_val=le.fit_transform(y_val)


In [17]:
y_val[0:5]

array([1, 1, 0, 1, 0])

In [18]:
test=pd.read_csv( '/content/drive/My Drive/dataset/OffenseEval2020/data/English/testset-taska.tsv',sep="\t")
X_test=test['tweet']
test.head()

id                                              tweet
0  1155791030211481600  To do the year add on course after third year ...
1  1155810478569984000  Wealth is not a matter of intelligence it's a ...
2  1155774940697808896  @USER Personally I think it looks better and g...
3  1155789922244222976                       @USER Good luck on the exams
4  1154994679345139700  I eat dick in the afternoon and call it lunchi...

In [19]:
x=train.iloc[323,1].lower().replace('@user','').replace('url','')
x=re.sub('[^A-Za-z]', ' ', x)
re.sub('http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|'
        '[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+','',x)

' hope your right  ok for me and you  let s see how it affects others   but in decency then pull your  joke  poll'

In [0]:
# Creating the training corpus
stop_words = set(stopwords.words("english")) 
lemmatizer = WordNetLemmatizer()

def preprocess(i):
  x=i.lower()
  x=x.replace('@user','')
  x=x.replace('@[\w\-]+','')
  #x=x.translate(str.maketrans('', '', string.punctuation))
  x = re.sub('[^A-Za-z]', ' ', x)
  #x=re.sub('\s+',' ',x)
  x=re.sub('http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|'
      '[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+','',x) #url
  #x = [lemmatizer.lemmatize(token) for token in x.split(" ")]
  #x = [word for word in x if not word in stop_words]
  #x=" ".join(x)
  return x


corpus_train = []
for i in X_train:
    corpus_train.append(preprocess(i))    

corpus_val = []
for i in X_val:
    corpus_val.append(preprocess(i)) 

corpus_test = []
for i in X_test:
    corpus_test.append(preprocess(i)) 


In [21]:
print(corpus_train[0])
print(corpus_val[0])
print(corpus_test[0])

first time i heard his name in camp  he seems to be the forgotten guychristian covington being disruptive so far today
 she should ask a few native americans what their take on this is 
to do the year add on course after third year or not to do you year add corse after third year


In [22]:
from keras.preprocessing.text import Tokenizer
from keras.preprocessing import sequence
max_words = 5000 #frequency of words to be kept
max_len = 200

tokenize = Tokenizer(num_words=max_words)
tokenize.fit_on_texts(corpus_train)
sequences = tokenize.texts_to_sequences(corpus_train)
word_index = tokenize.word_index
sequences_matrix = sequence.pad_sequences(sequences,maxlen=max_len)

Using TensorFlow backend.


In [0]:
val_sequences = tokenize.texts_to_sequences(corpus_val)
val_sequences_matrix = sequence.pad_sequences(val_sequences,maxlen=max_len)

test_sequences = tokenize.texts_to_sequences(corpus_test)
test_sequences_matrix = sequence.pad_sequences(test_sequences,maxlen=max_len)

In [24]:
num_words = min(max_words, len(word_index)) + 1
print(num_words)

5001


In [0]:
embedding_path1 = "drive/My Drive/dataset/OLID/wiki-news-300d-1M.vec"
embedding_path2 = "drive/My Drive/dataset/OLID/glove/glove.840B.300d.txt"
embed_size = 300

In [0]:
def get_coefs(word,*arr):
    return word, np.asarray(arr, dtype='float32')

def build_matrix(embedding_path, word_index):
    embedding_index = dict(get_coefs(*o.strip().split(" ")) for o in open(embedding_path))

    nb_words = min(max_words, len(word_index))
    embedding_matrix = np.zeros((nb_words + 1, embed_size))
    for word, i in word_index.items():
        if i >= max_words:
            continue
        embedding_vector = embedding_index.get(word)
        if embedding_vector is not None:
            embedding_matrix[i] = embedding_vector
    return embedding_matrix


In [0]:
fasttext=build_matrix(embedding_path1, word_index)
glove_emb=build_matrix(embedding_path2, word_index)

In [28]:
embedding_matrix=np.mean((fasttext,glove_emb),axis=0)
embedding_matrix.shape

(5001, 300)

In [0]:
from keras import backend as K
def f1(y_true, y_pred):
    '''
    metric from here 
    https://stackoverflow.com/questions/43547402/how-to-calculate-f1-macro-in-keras
    '''
    def recall(y_true, y_pred):
        """Recall metric.

        Only computes a batch-wise average of recall.

        Computes the recall, a metric for multi-label classification of
        how many relevant items are selected.
        """
        true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
        possible_positives = K.sum(K.round(K.clip(y_true, 0, 1)))
        recall = true_positives / (possible_positives + K.epsilon())
        return recall

    def precision(y_true, y_pred):
        """Precision metric.

        Only computes a batch-wise average of precision.

        Computes the precision, a metric for multi-label classification of
        how many selected items are relevant.
        """
        true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
        predicted_positives = K.sum(K.round(K.clip(y_pred, 0, 1)))
        precision = true_positives / (predicted_positives + K.epsilon())
        return precision
    precision = precision(y_true, y_pred)
    recall = recall(y_true, y_pred)
    return 2*((precision*recall)/(precision+recall+K.epsilon()))

In [0]:
# from keras.callbacks import Callback
# class EarlyStoppingByAccuracy(Callback):
#     def __init__(self, monitor='val_f1', value=0.87, verbose=0):
#         super(Callback, self).__init__()
#         self.monitor = monitor
#         self.value = value
#         self.verbose = verbose

#     def on_epoch_end(self, epoch, logs={}):
#         current = logs.get(self.monitor)
#         if current is None:
#             warnings.warn("Early stopping requires %s available!" % self.monitor, RuntimeWarning)

#         if current >= self.value:
#             if self.verbose > 0:
#                 print("Epoch %05d: early stopping THR" % epoch)
#             self.model.stop_training = True

In [0]:
#callbacks = EarlyStoppingByAccuracy(monitor='val_f1', value=0.89, verbose=1)

In [32]:
from keras.models import Sequential,Model
from keras.layers import Embedding,CuDNNGRU,Dense,Dropout,Bidirectional,GlobalMaxPool1D,GlobalAveragePooling1D, SpatialDropout1D,concatenate,Input
from keras.optimizers import RMSprop
from keras.initializers import Constant
from sklearn.utils import class_weight
from keras.callbacks import ModelCheckpoint
import tensorflow as tf
tf.logging.set_verbosity(tf.logging.ERROR)

inp=Input(shape=(max_len, ))
x=Embedding(num_words,embed_size,embeddings_initializer=Constant(embedding_matrix),input_length=max_len,trainable=False)(inp)
#x=Embedding(input_dim=max_words,output_dim=50,input_length=max_len)(inp)
x = SpatialDropout1D(0.2)(x)
x=Bidirectional(CuDNNGRU(150, return_sequences = True))(x)
avg_pool = GlobalAveragePooling1D()(x)
max_pool = GlobalMaxPool1D()(x)
conc = concatenate([avg_pool, max_pool])


x=Dropout(0.1)(conc)
out=Dense(64, activation="relu")(x)
out=Dense(32, activation="relu")(x)

out=Dense(1, activation="sigmoid")(x)

model=Model(inp,out)

mcp_save = ModelCheckpoint('.mdl_wts.hdf5', save_best_only=True, monitor='val_loss', mode='min')


model.compile(loss='binary_crossentropy', optimizer='adam', metrics=[f1])

class_weights = class_weight.compute_class_weight('balanced',np.unique(y_train),y_train)
class_weights=dict(enumerate(class_weights))

model.summary()

Model: "model_1"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            (None, 200)          0                                            
__________________________________________________________________________________________________
embedding_1 (Embedding)         (None, 200, 300)     1500300     input_1[0][0]                    
__________________________________________________________________________________________________
spatial_dropout1d_1 (SpatialDro (None, 200, 300)     0           embedding_1[0][0]                
__________________________________________________________________________________________________
bidirectional_1 (Bidirectional) (None, 200, 300)     406800      spatial_dropout1d_1[0][0]        
____________________________________________________________________________________________

In [33]:
model.fit(sequences_matrix,y_train,batch_size=512,epochs=10,verbose=2,class_weight=class_weights,
          validation_data=(val_sequences_matrix,y_val))

Train on 9075418 samples, validate on 13240 samples
Epoch 1/10
 - 2053s - loss: 0.1783 - f1: 0.8334 - val_loss: 0.6119 - val_f1: 0.7024
Epoch 2/10
 - 2049s - loss: 0.1618 - f1: 0.8493 - val_loss: 0.5983 - val_f1: 0.7064
Epoch 3/10
 - 2039s - loss: 0.1570 - f1: 0.8534 - val_loss: 0.6257 - val_f1: 0.7099
Epoch 4/10
 - 2147s - loss: 0.1541 - f1: 0.8559 - val_loss: 0.6139 - val_f1: 0.7081
Epoch 5/10
 - 2052s - loss: 0.1521 - f1: 0.8573 - val_loss: 0.6237 - val_f1: 0.7132
Epoch 6/10
 - 2148s - loss: 0.1507 - f1: 0.8584 - val_loss: 0.6065 - val_f1: 0.7154
Epoch 7/10
 - 2167s - loss: 0.1495 - f1: 0.8594 - val_loss: 0.5976 - val_f1: 0.7139
Epoch 8/10
 - 2106s - loss: 0.1485 - f1: 0.8600 - val_loss: 0.6159 - val_f1: 0.7154
Epoch 9/10
 - 2026s - loss: 0.1476 - f1: 0.8608 - val_loss: 0.6039 - val_f1: 0.7159
Epoch 10/10
 - 2031s - loss: 0.1471 - f1: 0.8610 - val_loss: 0.6127 - val_f1: 0.7167


In [0]:
model.save_weights('/content/drive/My Drive/dataset/OffenseEval2020/data/English/model.h5')

In [46]:
y_test = model.predict(test_sequences_matrix, batch_size=32, verbose=1)
np.save('sub1.npy',y_test)
np.savetxt("sub1_array.csv", y_test, delimiter=",")


8080/8080 [==============================] - 2s 275us/step


In [47]:
y_test[0:5]

array([[7.1939826e-04],
       [1.3548970e-02],
       [5.2251518e-03],
       [4.6050251e-03],
       [9.9661189e-01]], dtype=float32)

In [48]:
y_test[y_test>0.5]=1
y_test[y_test<0.5]=0
y_test[0:5]

array([[0.],
       [0.],
       [0.],
       [0.],
       [1.]], dtype=float32)

In [0]:
y_test=y_test.astype('int16').ravel()
y_test=le.inverse_transform(y_test)


In [50]:
y_test=pd.DataFrame(y_test,columns=['label'])
y_test=pd.concat([test['id'], y_test['label']], axis=1)

y_test.head()


id label
0  1155791030211481600   NOT
1  1155810478569984000   NOT
2  1155774940697808896   NOT
3  1155789922244222976   NOT
4  1154994679345139700   OFF

In [0]:
y_test.to_csv('/content/sub1.csv',index=False,header=None)


In [0]:
from sklearn.metrics import confusion_matrix, f1_score, precision_score, recall_score
f1_score(y_test, y_pred, average="macro")

In [0]:
# import keras
# keras.backend.clear_session()